#!/bin/zsh
#
# .aliases - Set whatever shell aliases you want.
#

# tar
alias tarls="tar -tvf"
alias untar="tar -xf"

# url encode/decode
alias urldecode='python3 -c "import sys, urllib.parse as ul; \
    print(ul.unquote_plus(sys.argv[1]))"'
alias urlencode='python3 -c "import sys, urllib.parse as ul; \
    print (ul.quote_plus(sys.argv[1]))"'

alias quit='exit'
