#!/bin/zsh
#
# .zstyles - Set zstyle settings for plugins that need them.
#

#
# Antidote
#

# zstyle ':antidote:bundle' file ${ZDOTDIR:-~}/.zplugins.txt
# zstyle ':antidote:bundle' use-friendly-names 'yes'
#

zstyle ':zephyr:plugin:prompt' theme starship zephyr

#
# OMZ
#

zstyle :omz:plugins:iterm2 shell-integration yes
